# ABOUTME: Fly.io configuration for magnet-9rl (US Hub IRC server)
# ABOUTME: Primary IRC server deployed in Chicago region with OpenSSL optimization

app = "magnet-9rl"
primary_region = "ord"

[vm]
  memory = "1gb"
  cpus = 1

[[restart]]
  policy = "on-failure"

[build]
  dockerfile = "solanum/Dockerfile"

[mounts]
  source = "magnet_9rl_data"
  destination = "/opt/solanum/etc/"

# [mounts]
#   source = "magnet_9rl_data"
#   destination = "/opt/solanum/var"

[env]
  SERVER_NAME = "magnet-9rl"
  SERVER_SID = "9RL"
  SERVER_DESCRIPTION = "Magnet IRC Network - US Hub"
  TAILSCALE_DOMAIN = "camel-kanyu.ts.net"
  ADMIN_NAME = "Chris Prather"
  ADMIN_DESCRIPTION = "Current MagNET Wrangler"
  ADMIN_EMAIL = "chris@prather.org"
  SSL_DOMAINS = "magnet-9rl.fly.dev,magnet-9rl.kowloon.social,magnet-9rl.irc.perl.org"


[[services]]
  internal_port = 6667
  protocol = "tcp"

  [[services.ports]]
    port = 6667

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"

[[services]]
  internal_port = 6697
  protocol = "tcp"

  [[services.ports]]
    port = 6697

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"

[[services]]
  internal_port = 7000
  protocol = "tcp"

  [[services.ports]]
    port = 7000

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"
