# ABOUTME: Fly.io configuration for magnet-1eu (EU IRC server)
# ABOUTME: Secondary IRC server deployed in Amsterdam region with OpenSSL optimization

app = "magnet-1eu"
primary_region = "ams"

[vm]
  memory = "1gb"
  cpus = 1

[build]
  dockerfile = "../../solanum/Dockerfile"

[mounts]
  source = "magnet_1eu_data"
  destination = "/opt/solanum/var"

[env]
  SERVER_NAME = "magnet-1eu"
  SERVER_SID = "1EU"
  SERVER_DESCRIPTION = "Magnet IRC Network - EU Server"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[services]]
  internal_port = 6667
  protocol = "tcp"

  [[services.ports]]
    port = 6667

[[services]]
  internal_port = 6697
  protocol = "tcp"

  [[services.ports]]
    port = 6697

[[services]]
  internal_port = 7000
  protocol = "tcp"

  [[services.ports]]
    port = 7000