# ABOUTME: Fly.io configuration for magnet-1eu (EU IRC server)
# ABOUTME: Secondary IRC server deployed in Amsterdam region with OpenSSL optimization

app = "magnet-1eu"
primary_region = "ams"

[vm]
  memory = "512mb"
  cpus = 1

[[restart]]
  policy = "on-failure"

[build]
  dockerfile = "solanum/Dockerfile"
  context = "../.."
  [build.args]
    SERVER_NAME = "magnet-1eu"

[mounts]
  source = "magnet_1eu_data_1gb"
  destination = "/opt/solanum/var"

[env]
  SERVER_NAME = "magnet-1eu"
  SERVER_SID = "1EU"
  SERVER_DESCRIPTION = "Magnet IRC Network - EU Server"
  TAILSCALE_DOMAIN = "camel-kanyu.ts.net"
  ADMIN_NAME = "Chris Prather"
  ADMIN_DESCRIPTION = "Current MagNET Wrangler"
  ADMIN_EMAIL = "chris@prather.org"
  SSL_DOMAINS = "magnet-1eu.fly.dev,magnet-1eu.kowloon.social,magnet-1eu.irc.perl.org"


[[services]]
  internal_port = 6667
  protocol = "tcp"

  [[services.ports]]
    port = 6667

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"

[[services]]
  internal_port = 6697
  protocol = "tcp"

  [[services.ports]]
    port = 6697

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"

[[services]]
  internal_port = 7000
  protocol = "tcp"

  [[services.ports]]
    port = 7000

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "5s"