# ABOUTME: Fly.io configuration for magnet-atheme (IRC services)
# ABOUTME: Atheme IRC services deployed in Chicago region for US operation

app = "magnet-atheme"
primary_region = "ord"

[vm]
  memory = "512mb"
  cpus = 1

[[restart]]
  policy = "on-failure"

[build]
  dockerfile = "atheme/Dockerfile"

[mounts]
  source = "magnet_atheme_data"
  destination = "/opt/atheme/etc/"

[env]
  SERVER_NAME = "magnet-atheme"
  ATHEME_NETWORK = "Magnet"
  ATHEME_HUB_SERVER = "magnet-9RL"
  ATHEME_HUB_HOSTNAME = "magnet-9rl.internal"
  TAILSCALE_DOMAIN = "camel-kanyu.ts.net"
  ADMIN_NAME = "Chris Prather"
  ADMIN_EMAIL = "chris@prather.org"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true

  [[http_service.checks]]
    grace_period = "90s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/health"

[[services]]
  internal_port = 6667
  protocol = "tcp"

  [[services.ports]]
    port = 6667
